Accounts/urls.py
from django.conf.urls import patterns, url, include
from Accounts import views


urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^accounts/', include('registration.backends.default.urls'), name='register'),
    )

manager_app/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',"Accounts.views.index"),
    #url(r'^password/reset/done/$',auth_views.password_reset_done,name='password_reset_done',),
    url(
        r'^password/reset/done/$',
        auth_views.password_reset,
        {'template_name': 'registration/password_reset_form.html'},
        name='auth_password_reset',
    ),
    url(r'^users/', include('Accounts.urls'),),
    url(r'^admin/', include(admin.site.urls)),


)


if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
         'serve',
         {'document_root': settings.MEDIA_ROOT}), )

Accounts/models.py
from django.db import models
from django.contrib.auth.models import User
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    # The additional attributes we wish to include.
    phonenumber = models.CharField(max_length=20, default="+233")
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

Accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from models import UserProfile
from registration.forms import RegistrationForm

class UserProfileForm(RegistrationForm):
    username        = forms.CharField(max_length=100)
    email           = forms.EmailField()
    #first_name      = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())



    class Meta:
        model = UserProfile
        fields = ('username','email', 'picture','password1','password2')
    def clean_username(self):
                username = self.cleaned_data['username']
                try:
                        User.objects.get(username=username)
                except User.DoesNotExist:
                        return username
                raise forms.ValidationError( username + " is already taken, please enter another.")

    def clean_email(self):
                email = self.cleaned_data['email']
                try:
                        User.objects.get(email=email)
                except User.DoesNotExist:
                        return email
                raise forms.ValidationError( email + " is already taken, please enter another.")


    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

Accounts/views.py
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse

from django.shortcuts import render, render_to_response

from Accounts.forms import UserProfileForm
from django.template import RequestContext

def index(request):
    context = RequestContext(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return render_to_response('profile.html', {}, context)
            else:
                error_message="Your have not activated your account. Please check your email and validate it"
                return render_to_response('registration/login.html', {'error_message':error_message}, context)
                # An inactive account was used - no logging in!

        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            error_message="Login details invalid"
            return render_to_response('registration/login.html', {'error_message':error_message}, context)

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('registration/login.html', {}, context)


def profile(request):
    context=RequestContext(request)
    return render_to_response("profile.html",{},context)

def register(request):
    context = RequestContext(request)
    registered = False
    some_errors= False
    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        profile_form = UserProfileForm(data=request.POST)
        if profile_form.is_valid():
            # Save the user's form data to the database.
            user = User.objects.create_user(username=profile_form.cleaned_data['username'], \
                                            email = profile_form.cleaned_data['email'], \
                                            password = profile_form.cleaned_data['password'], \
                                            first_name=profile_form.cleaned_data['first_name'])
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                print "Yes the picture exists"
            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True


        else:
            some_errors=True
            return render_to_response(
            'signup.html',
            { 'profile_form': profile_form, 'registered': registered,'some_errors':some_errors},
            context)

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:

        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render_to_response(
            'signup.html',
            { 'profile_form': profile_form, 'registered': registered},
            context)

templates/account_confirmation.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Edit profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap-responsive.css" rel="stylesheet">
    <link href="css/extras.css" rel="stylesheet">
</head>
<body>

	<div class="options">
    	<a href="#" class="tooltip-test" onclick="javascript:window.print();" data-original-title="Print CV"><img src="img/print.png" border="0"></a>
        <a href="#" class="tooltip-test" data-original-title="Download"><img src="img/download.png"></a>
	</div>

    <div class="container well">
        <div class="row">
            <div class="span12">
                <div id="data">
                	<h2>Congratulations on your registration. A confirmation email has been sent to '''your email'''please confirm to view your profile</h2>
                </div>
                <div id="social">
                    <a href="#" class="tooltip-test" data-original-title="Facebook"><img src="img/facebookpb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="Flickr"><img src="img/flickrpb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="Google +"><img src="img/googlepb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="My Space"><img src="img/myspacepb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="Twitter"><img src="img/twitterpb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="Youtube"><img src="img/youtubepb.png"></a>
              </div>
            </div>
        </div>
    </div>
    
    <div class="container well">
        <div class="row">
            <div class="span12">
                <h1 class="pull-right"><button type="submit" class="btn btn-info btn-large">Home Page</button></h1>
            </div>
        </div>
    </div>
    
    
    
    
<!-- JAVASCRIPT INSERTS -->
<script src="js/jquery.js"></script>
<script src="js/bootstrap-alert.js"></script>
<script src="js/bootstrap-collapse.js"></script>
<script src="js/bootstrap-dropdown.js"></script>
<script src="js/bootstrap-modal.js"></script>
<script src="js/bootstrap-tab.html"></script>
<script src="js/bootstrap-prettify.js"></script>
<script src="js/bootstrap-tooltip.js"></script>
<script src="js/bootstrap-transition.js"></script>
<script src="js/bootstrap-typeahead.js"></script>
</body>


</html>

templates/dummy.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>

    <body>


        {% if registered %}
         <strong>You are already registered</strong>
        <a href="/">Return to the homepage.</a><br />
        {% else %}
         <strong>register here!</strong><br />

        <form id="user_form" method="post" action="/users/register/"
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
              <!-- {{ profile_form.as_p }}-->
                    <div style="color: #ffff00"> {{ profile_form.username.errors }}
                       {{ profile_form.email.errors }}
                       {{ profile_form.first_name.errors }}
                       {{ profile_form.phonenumber.errors }}
                    </div>

 <input id="id_username" maxlength="100" name="username" type="text" /></p>

 <input id="id_first_name" name="first_name" type="text" />
 <input id="id_email" name="email" type="email" />

 <input id="id_phonenumber" maxlength="20" name="phonenumber" type="text" /></p>
<!-- <input id="id_picture" name="picture" type="file" /></p>-->
 <input id="id_password" name="password" type="password" /></p>

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
    </body>
</html>



  {% if registered %}

  {% else %}

  {% endif %}

templates/edit_profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Edit Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap-responsive.css" rel="stylesheet">
    <link href="css/extras.css" rel="stylesheet">
</head>
<body>

	<div class="options">
    	<a href="#" class="tooltip-test" onclick="javascript:window.print();" data-original-title="Print CV"><img src="img/print.png" border="0"></a>
        <a href="#" class="tooltip-test" data-original-title="Download"><img src="img/download.png"></a>
	</div>

    <div class="container well">
        <div class="row">
            <div class="span12">
                <div id="photo"><img src="img/user.png" width="186px"></div>
                <div id="data">
                	<table class="table">
                      <tbody>
                        <tr>
                          <td><h3>Birth</h3></td>
                          <td><input type='text'></td>
                        </tr>
                        <tr>
                          <td><h3>Address</h3></td>
                          <td><input type='text'></td>
                        </tr>
                        <tr>
                          <td><h3>Phone</h3></td>
                          <td><input type='text'></td>
                        </tr>
                        <tr>
                          <td><h3>Mail</h3></td>
                          <td><input type='text'></td>
                        </tr>
                      </tbody>
                    </table>
                </div>
                <div id="social">
                    <a href="#" class="tooltip-test" data-original-title="Facebook"><img src="../img/facebookpb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="Flickr"><img src="../img/flickrpb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="Google +"><img src="../img/googlepb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="My Space"><img src="../img/myspacepb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="Twitter"><img src="../img/twitterpb.png"></a>
                    <a href="#" class="tooltip-test" data-original-title="Youtube"><img src="../img/youtubepb.png"></a>
              </div>
            </div>
        </div>
    </div>
    
    <div class="container well">
        <div class="row">
            <div class="span12">

                <h1 class="pull-right"><button type="submit" class="btn btn-info btn-large">Save New Changes</button></h1>
            </div>
        </div>
    </div>
    
    
    
    
<!-- JAVASCRIPT INSERTS -->
<script src="js/jquery.js"></script>
<script src="js/bootstrap-alert.js"></script>
<script src="js/bootstrap-collapse.js"></script>
<script src="js/bootstrap-dropdown.js"></script>
<script src="js/bootstrap-modal.js"></script>
<script src="js/bootstrap-tab.html"></script>
<script src="js/bootstrap-prettify.js"></script>
<script src="js/bootstrap-tooltip.js"></script>
<script src="js/bootstrap-transition.js"></script>
<script src="js/bootstrap-typeahead.js"></script>
</body>


</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Login, registration forms">
    <meta name="author" content="Seong Lee">

    <title>Home Page</title>

    <!-- Stylesheets -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/animation.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/checkbox/orange.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/preview.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/authenty.css" rel="stylesheet">

    <!-- Font Awesome CDN -->
    <link href="{{ STATIC_URL }}css/font-awesome.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css'>


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<section id="authenty_preview">
    <section id="signin_main" class="authenty signin-main">
        <div class="section-content">
            <div class="wrap">
                <div class="container">
                    <div class="form-wrap">
                        <div class="row">
                            <div class="title" data-animation="fadeInDown" data-animation-delay=".8s">
                                <h1>S-track</h1>
                                <h5>Authenticate your account by signing in</h5>
                            </div>
                            <div id="form_1" data-animation="bounceIn">
                                <div class="form-header">
                                    <i class="fa fa-user"></i>
                                </div>
                                <div class="form-main">
                                    <form>
                                        <div class="form-group">
                                            <input type="text" id="un_1" class="form-control" placeholder="Username" required="required">
                                            <input type="password" id="pw_1" class="form-control" placeholder="Password" required="required">
                                        </div>
                                        <button id="signIn_1" type="submit" class="btn btn-block signin">Sign In</button>
                                    </form>
                                </div>
                                <div class="form-footer">
                                    <div class="row">
                                        <div class="col-xs-7">
                                            <i class="fa fa-unlock-alt"></i>
                                            <a href="#password_recovery" id="forgot_from_1">Forgot password?</a>
                                        </div>
                                        <div class="col-xs-5">
                                            <i class="fa fa-check"></i>
                                            <a href="/users/register" id="signup_from_1">Sign Up</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>









</section>


<!-- js library -->
<script src="{{ STATIC_URL }}js/jquery.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.icheck.min.js"></script>
<script src="{{ STATIC_URL }}js/waypoints.min.js"></script>

<!-- authenty js -->
<script src="{{ STATIC_URL }}js/authenty.js"></script>

<!-- preview scripts -->
<script src="{{ STATIC_URL }}js/preview/jquery.malihu.PageScroll2id.js"></script>
<script src="{{ STATIC_URL }}js/preview/jquery.address-1.6.min.js"></script>
<script src="{{ STATIC_URL }}js/preview/scrollTo.min.js"></script>
<script src="{{ STATIC_URL }}js/preview/init.js"></script>


<!-- preview scripts -->
<script>
    (function($) {

        // get full window size
        $(window).on('load resize', function(){
            var w = $(window).width();
            var h = $(window).height();

            $('section').height(h);

        ;


        });

        // scrollTo plugin
        $('#signup_from_1').scrollTo({ easing: 'easeInOutQuint', speed: 1500 });
        $('#forgot_from_1').scrollTo({ easing: 'easeInOutQuint', speed: 1500 });
        $('#signup_from_2').scrollTo({ easing: 'easeInOutQuint', speed: 1500 });
        $('#forgot_from_2').scrollTo({ easing: 'easeInOutQuint', speed: 1500 });
        $('#forgot_from_3').scrollTo({ easing: 'easeInOutQuint', speed: 1500 });

        // $('html, body').animate({
        //      'scrollTop' : $("#signup_window").position().top
         // });




        // set focus on input
        var firstInput = $('section').find('input[type=text], input[type=email]').filter(':visible:first');

        if (firstInput != null) {
            firstInput.focus();
        }

        $('section').waypoint(function (direction) {
            var target = $(this).find('input[type=text], input[type=email]').filter(':visible:first');
            target.focus();
        }, {
            offset: 300
        }).waypoint(function (direction) {
            var target = $(this).find('input[type=text], input[type=email]').filter(':visible:first');
            target.focus();
        }, {
            offset: -400
        });


        // animation handler
        $('[data-animation-delay]').each(function () {
            var animationDelay = $(this).data("animation-delay");
            $(this).css({
                "-webkit-animation-delay": animationDelay,
                "-moz-animation-delay": animationDelay,
                "-o-animation-delay": animationDelay,
                "-ms-animation-delay": animationDelay,
                "animation-delay": animationDelay
            });
        });

        $('[data-animation]').waypoint(function (direction) {
            if (direction == "down") {
                $(this).addClass("animated " + $(this).data("animation"));
            }
        }, {
            offset: '90%'
        }).waypoint(function (direction) {
            if (direction == "up") {
                $(this).removeClass("animated " + $(this).data("animation"));
            }
        }, {
            offset: '100%'
        });

         $('html, body').animate({
            scrollTop: $('#signup_window').offset().top
         }, 'slow');

    })(jQuery);
</script>

</body>

</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Login, registration forms">
    <meta name="author" content="Seong Lee">

    <title>Home Page</title>

    <!-- Stylesheets -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/animation.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/checkbox/orange.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/preview.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/authenty.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
    <!-- Font Awesome CDN -->
    <link href="{{ STATIC_URL }}css/font-awesome.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css'>


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <section id="signup_window" class="authenty signup-window">
        <div class="section-content">
            <div class="wrap">
                <div class="container">
                    <div class="row form-wrap" data-animation="bounceIn">
                        <i class="fa fa-times-circle"></i>
                        <div class="title">
                            <h3 id="form-title">Create an account</h3>
                        </div>
                        <div class="col-xs-12 col-sm-5 col-md-4 col-md-offset-1">
                            <div class="sns-signin">
                                <a class="btn btn-primary" href="#">
                                    <i class="fa fa-facebook"></i>Sign in via Facebook</a>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-2 col-sm-1">
                            <div class="horizontal-divider"></div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-4">
                            <div class="normal-signup">
                                <form id="user_form" method="post" action="/users/register/" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <p id="validation_error">{{ profile_form.non_field_errors.as_text }}</p>
                                   <div class="form-group">
                                        <p id="validation_error"> {{ profile_form.username.errors.as_text }} </p>
                                        <input type="text" class="form-control" placeholder="Username"  name="username" id="id_username" value="{{ profile_form.data.username }}">
                                        <p id="validation_error"> {{ profile_form.email.errors.as_text }} </p>
                                        <input type="email" class="form-control" placeholder="Email"  name="email" id="id_email" value="{{ profile_form.data.email }}">
                                        <p id="validation_error"> {{ profile_form.first_name.errors.as_text }} </p>
                                        <input type="text" class="form-control" placeholder="First name" name="first_name" id="id_first_name" value="{{ profile_form.data.first_name }}">
                                        <p id="validation_error"> {{ profile_form.phonenumber.errors.as_text }} </p>
                                        <input type="text" class="form-control" placeholder="Phone Number" name="phonenumber" id="id_phonenumber" value="{{ profile_form.data.phonenumber }}">
                                        <p id="validation_error"> {{ profile_form.password.errors.as_text }} </p>
                                        <input type="password" class="form-control" placeholder="Enter Password" name="password" id="id_password" >
                                       <input type="password" class="form-control" placeholder="Re-enter Password" name="password1" id="id_password2">
                                    </div>
                                    <div class="row">
                                        <!-- <div class="col-md-6">
                                            <a href="#password_recovery" id="forgot_from_3">need help?</a>
                                        </div> -->
                                        <div class="col-md-5 col-md-offset-7">
                                            <button type="submit" class="btn btn-block signup">Sign Up</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>




</section>


<!-- js library -->
<script src="{{ STATIC_URL }}js/jquery.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.icheck.min.js"></script>
<script src="{{ STATIC_URL }}js/waypoints.min.js"></script>

<!-- authenty js -->
<script src="{{ STATIC_URL }}js/authenty.js"></script>

<!-- preview scripts -->
<script src="{{ STATIC_URL }}js/preview/jquery.malihu.PageScroll2id.js"></script>
<script src="{{ STATIC_URL }}js/preview/jquery.address-1.6.min.js"></script>
<script src="{{ STATIC_URL }}js/preview/scrollTo.min.js"></script>
<script src="{{ STATIC_URL }}js/preview/init.js"></script>


<!-- preview scripts -->
<script>
    (function($) {

        // get full window size
        $(window).on('load resize', function(){
            var w = $(window).width();
            var h = $(window).height();

            $('section').height(h);

        });



        // set focus on input
        var firstInput = $('section').find('input[type=text], input[type=email]').filter(':visible:first');

        if (firstInput != null) {
            firstInput.focus();
        }
       $('[data-animation]').waypoint(function (direction) {
            if (direction == "down") {
                $(this).addClass("animated " + $(this).data("animation"));
            }
        }, {
            offset: '90%'
        }).waypoint(function (direction) {
            if (direction == "up") {
                $(this).removeClass("animated " + $(this).data("animation"));
            }
        }, {
            offset: '100%'
        });

         $('html, body').animate({
            scrollTop: $('#signup_window').offset().top
         }, 'slow');

    })(jQuery);
</script>

</body>

</html>